### ISSUE TITLE
Windows 7 Error

### ISSUE THREAD

**Issue by KuRuMaA** [Nenkai/GTEventGenerator#2]
I try to run the program in a Windows 7 laptop and an error shows:
An error occured in the editor, please report to the creator: System.BadImageFormatException: Could not load file or assembly 'Presentation Framework.Aero2, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) File name: 'Presentation Framework.Aero2, PublicKeyToken=31bf3856ad364e35' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly location Hint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forintrospection, Boolean suppress Security Checks)
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codebase, Evidence assembly Security, RuntimeAssembly location Hint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throw OnFileNotFound, Boolean forintrospection, Boolean suppressSecurity Checks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assembly Ref, Evidence assembly Security, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forintrospection, Boolean suppress Security Checks)
at System.Reflection.Assembly.Load(AssemblyName assembly Ref) at System.Windows.Bam 2006.Bam 2006SchemaContext.Resolve Assembly(Bam Assembly bamlAssembly) at System.Windows.Bam|2006.Bam2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType) at System.Windows.Bam|2006.Bam|2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeld) at System.Windows.Bam 2006.Bam 2006SchemaContext. GetXamlType(Int16 typeld) at System.Windows.Bam 2006.Bam 2006 Reader.Process_ElementStart at System.Windows.Bam 2006.Bam 2006 Reader.Process OneBamRecord at System.Windows.Bam 2006.Bam 2006 Reader.ReadObject(KeyRecord record) at System.Windows.ResourceDictionary.CreateObject(Key Record key) at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache) at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache) at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache) at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache) at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache) at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
at System.Windows.ResourceDictionary.FetchResource(Object resourceKey, Boolean allowDeferred ResourceReference, Boolean mustReturnDeferred ResourceReference, Boolean canCacheAsThemeResource, Boolean& canCache)
at System.Windows.FrameworkElement.Find ResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferred ResourceReference, Boolean mustReturnDeferred ResourceReference, DependencyObject boundary Element, Boolean isimplicitStyleLookup, Object & source)
at System.Windows.FrameworkElement.FindImplicitStyleResource(FrameworkElement fe, Object resourceKey, Object & source) at System.Windows.FrameworkElement. GetRawValue(DependencyProperty dp, Property Metadata metadata, EffectiveValueEntry & entry)
ndows.FrameworkElement.EvaluateBaseValueCore(DependencyProperty dp, Property Metadata metadata, EffectiveValueEntry & newEntry) at System.Windows.DependencyObject.EvaluateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, Property Metadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry newEntry, Operation Type operation Type)
at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, Property Metadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWith DeferredReference, Boolean coerceWithCurrentValue, Operation Type operation Type)
at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue) at System.Windows.FrameworkElement.UpdateStyleProperty at System.Windows.FrameworkElement.OnInitialized(EventArgs e) at System.Windows.Controls.MenuItem.OnInitialized(EventArgs e) at System.Windows.FrameworkElement.TryFireInitialized at System.Windows.FrameworkElement.Endinit at System.Windows.Controls.ItemsControl.EndInit at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xaml Type, Object obj, Boolean begin)

I would really appreciate if someone would share a solution to my problem

**Comment by Razer2015** [comment]
1. Rename the current **PresentationFramework.Aero2.dll** to **PresentationFramework.Aero2.dll.bak**. 
2. Download the following zip [PresentationFramework.Aero2.zip](https://github.com/Nenkai/GTEventGenerator/files/9070073/PresentationFramework.Aero2.zip) and extract the **PresentationFramework.Aero2.dll** from it along side the GTEventGenerator2.exe file. 

Does it still give you the same error?

**Comment by KuRuMaA** [comment]
It doesnt give me the error now. Thank you very much!
